// SPDX-License-Identifier: AGPL-3.0-only
// Regenerates src/version.ts from package.json. Wired into the npm "version" lifecycle
// (see package.json scripts.version) so the exported VERSION constant can never drift from
// the published package version; test/version.ts gates publishing on the two matching.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const { version } = JSON.parse(readFileSync(root + "package.json", "utf8"));

const body = `// SPDX-License-Identifier: AGPL-3.0-only
// GENERATED by scripts/sync-version.mjs from package.json — do not edit by hand.

/** The meshstep package version. Record it alongside any cached mesh or persisted face/edge
 * selections: entity ids are stable across versions (see README "Identity & versioning"), but
 * the triangulation under them changes between releases, so cached geometry must be keyed to
 * the version that produced it. */
export const VERSION = "${version}";
`;

writeFileSync(root + "src/version.ts", body);
console.log(`src/version.ts <- ${version}`);
