// SPDX-License-Identifier: AGPL-3.0-only
// GENERATED by scripts/sync-version.mjs from package.json — do not edit by hand.

/** The meshstep package version. Record it alongside any cached mesh or persisted face/edge
 * selections: entity ids are stable across versions (see README "Identity & versioning"), but
 * the triangulation under them changes between releases, so cached geometry must be keyed to
 * the version that produced it. */
export const VERSION = "0.1.0";
